services:
  grpc:
    container_name: go-grpc
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    command: air -c .air.toml
    volumes:
      - ./src:/go/src
    ports:
      - "8080:8080"
    environment:
      - ENV
      - PORT
    tty: true
    stdin_open: true