// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: proto/sample/sample.proto

package sample

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空のリクエストパラメータ
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_sample_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{0}
}

// Helloメソッドのレスポンス結果
type HelloResponseBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponseBody) Reset() {
	*x = HelloResponseBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponseBody) ProtoMessage() {}

func (x *HelloResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponseBody.ProtoReflect.Descriptor instead.
func (*HelloResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponseBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HelloAddTextメソッドのリクエストパラメータ
type HelloAddTextRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// テキスト
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAddTextRequestBody) Reset() {
	*x = HelloAddTextRequestBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAddTextRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAddTextRequestBody) ProtoMessage() {}

func (x *HelloAddTextRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAddTextRequestBody.ProtoReflect.Descriptor instead.
func (*HelloAddTextRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAddTextRequestBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// HelloAddTextメソッドのレスポンス結果
type HelloAddTextResponseBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAddTextResponseBody) Reset() {
	*x = HelloAddTextResponseBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAddTextResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAddTextResponseBody) ProtoMessage() {}

func (x *HelloAddTextResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAddTextResponseBody.ProtoReflect.Descriptor instead.
func (*HelloAddTextResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAddTextResponseBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sample_sample_proto protoreflect.FileDescriptor

const file_proto_sample_sample_proto_rawDesc = "" +
	"\n" +
	"\x19proto/sample/sample.proto\x12\x06sample\x1a\x17validate/validate.proto\"\a\n" +
	"\x05Empty\"-\n" +
	"\x11HelloResponseBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x17HelloAddTextRequestBody\x12\x1b\n" +
	"\x04text\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04text\"4\n" +
	"\x18HelloAddTextResponseBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x99\x01\n" +
	"\rSampleService\x123\n" +
	"\x05Hello\x12\r.sample.Empty\x1a\x19.sample.HelloResponseBody\"\x00\x12S\n" +
	"\fHelloAddText\x12\x1f.sample.HelloAddTextRequestBody\x1a .sample.HelloAddTextResponseBody\"\x00B\vZ\tpb/sampleb\x06proto3"

var (
	file_proto_sample_sample_proto_rawDescOnce sync.Once
	file_proto_sample_sample_proto_rawDescData []byte
)

func file_proto_sample_sample_proto_rawDescGZIP() []byte {
	file_proto_sample_sample_proto_rawDescOnce.Do(func() {
		file_proto_sample_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sample_sample_proto_rawDesc), len(file_proto_sample_sample_proto_rawDesc)))
	})
	return file_proto_sample_sample_proto_rawDescData
}

var file_proto_sample_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sample_sample_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: sample.Empty
	(*HelloResponseBody)(nil),        // 1: sample.HelloResponseBody
	(*HelloAddTextRequestBody)(nil),  // 2: sample.HelloAddTextRequestBody
	(*HelloAddTextResponseBody)(nil), // 3: sample.HelloAddTextResponseBody
}
var file_proto_sample_sample_proto_depIdxs = []int32{
	0, // 0: sample.SampleService.Hello:input_type -> sample.Empty
	2, // 1: sample.SampleService.HelloAddText:input_type -> sample.HelloAddTextRequestBody
	1, // 2: sample.SampleService.Hello:output_type -> sample.HelloResponseBody
	3, // 3: sample.SampleService.HelloAddText:output_type -> sample.HelloAddTextResponseBody
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sample_sample_proto_init() }
func file_proto_sample_sample_proto_init() {
	if File_proto_sample_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sample_sample_proto_rawDesc), len(file_proto_sample_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sample_sample_proto_goTypes,
		DependencyIndexes: file_proto_sample_sample_proto_depIdxs,
		MessageInfos:      file_proto_sample_sample_proto_msgTypes,
	}.Build()
	File_proto_sample_sample_proto = out.File
	file_proto_sample_sample_proto_goTypes = nil
	file_proto_sample_sample_proto_depIdxs = nil
}
