// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: proto/sample/sample.proto

package sample

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空のリクエストパラメータ
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_sample_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{0}
}

// Helloメソッドのレスポンス結果
type HelloResponseBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponseBody) Reset() {
	*x = HelloResponseBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponseBody) ProtoMessage() {}

func (x *HelloResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponseBody.ProtoReflect.Descriptor instead.
func (*HelloResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponseBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HelloAddTextメソッドのリクエストパラメータ
type HelloAddTextRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// テキスト
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAddTextRequestBody) Reset() {
	*x = HelloAddTextRequestBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAddTextRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAddTextRequestBody) ProtoMessage() {}

func (x *HelloAddTextRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAddTextRequestBody.ProtoReflect.Descriptor instead.
func (*HelloAddTextRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAddTextRequestBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// HelloAddTextメソッドのレスポンス結果
type HelloAddTextResponseBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAddTextResponseBody) Reset() {
	*x = HelloAddTextResponseBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAddTextResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAddTextResponseBody) ProtoMessage() {}

func (x *HelloAddTextResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAddTextResponseBody.ProtoReflect.Descriptor instead.
func (*HelloAddTextResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAddTextResponseBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HelloServerStreamメソッドのリクエストパラメータ
type HelloServerStreamRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// テキスト
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloServerStreamRequestBody) Reset() {
	*x = HelloServerStreamRequestBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloServerStreamRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloServerStreamRequestBody) ProtoMessage() {}

func (x *HelloServerStreamRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloServerStreamRequestBody.ProtoReflect.Descriptor instead.
func (*HelloServerStreamRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{4}
}

func (x *HelloServerStreamRequestBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// HelloServerStreamメソッドのレスポンス結果
type HelloServerStreamResponseBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloServerStreamResponseBody) Reset() {
	*x = HelloServerStreamResponseBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloServerStreamResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloServerStreamResponseBody) ProtoMessage() {}

func (x *HelloServerStreamResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloServerStreamResponseBody.ProtoReflect.Descriptor instead.
func (*HelloServerStreamResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{5}
}

func (x *HelloServerStreamResponseBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HelloClientStreamメソッドのリクエストパラメータ
type HelloClientStreamRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// テキスト
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloClientStreamRequestBody) Reset() {
	*x = HelloClientStreamRequestBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloClientStreamRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloClientStreamRequestBody) ProtoMessage() {}

func (x *HelloClientStreamRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloClientStreamRequestBody.ProtoReflect.Descriptor instead.
func (*HelloClientStreamRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{6}
}

func (x *HelloClientStreamRequestBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// HelloClientStreamメソッドのレスポンス結果
type HelloClientStreamResponseBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloClientStreamResponseBody) Reset() {
	*x = HelloClientStreamResponseBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloClientStreamResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloClientStreamResponseBody) ProtoMessage() {}

func (x *HelloClientStreamResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloClientStreamResponseBody.ProtoReflect.Descriptor instead.
func (*HelloClientStreamResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{7}
}

func (x *HelloClientStreamResponseBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HelloBidirectionalStreamメソッドのリクエストパラメータ
type HelloBidirectionalStreamRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// テキスト
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloBidirectionalStreamRequestBody) Reset() {
	*x = HelloBidirectionalStreamRequestBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloBidirectionalStreamRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloBidirectionalStreamRequestBody) ProtoMessage() {}

func (x *HelloBidirectionalStreamRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloBidirectionalStreamRequestBody.ProtoReflect.Descriptor instead.
func (*HelloBidirectionalStreamRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{8}
}

func (x *HelloBidirectionalStreamRequestBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// HelloBidirectionalStreamメソッドのレスポンス結果
type HelloBidirectionalStreamResponseBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloBidirectionalStreamResponseBody) Reset() {
	*x = HelloBidirectionalStreamResponseBody{}
	mi := &file_proto_sample_sample_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloBidirectionalStreamResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloBidirectionalStreamResponseBody) ProtoMessage() {}

func (x *HelloBidirectionalStreamResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloBidirectionalStreamResponseBody.ProtoReflect.Descriptor instead.
func (*HelloBidirectionalStreamResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{9}
}

func (x *HelloBidirectionalStreamResponseBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// エラーレスポンス
type ErrResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージ
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrResponse) Reset() {
	*x = ErrResponse{}
	mi := &file_proto_sample_sample_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrResponse) ProtoMessage() {}

func (x *ErrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrResponse.ProtoReflect.Descriptor instead.
func (*ErrResponse) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{10}
}

func (x *ErrResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sample_sample_proto protoreflect.FileDescriptor

const file_proto_sample_sample_proto_rawDesc = "" +
	"\n" +
	"\x19proto/sample/sample.proto\x12\x06sample\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\a\n" +
	"\x05Empty\"-\n" +
	"\x11HelloResponseBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x17HelloAddTextRequestBody\x12\x1b\n" +
	"\x04text\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04text\"4\n" +
	"\x18HelloAddTextResponseBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\x1cHelloServerStreamRequestBody\x12\x1b\n" +
	"\x04text\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04text\"9\n" +
	"\x1dHelloServerStreamResponseBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\x1cHelloClientStreamRequestBody\x12\x1b\n" +
	"\x04text\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04text\"9\n" +
	"\x1dHelloClientStreamResponseBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"#HelloBidirectionalStreamRequestBody\x12\x1b\n" +
	"\x04text\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04text\"@\n" +
	"$HelloBidirectionalStreamResponseBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\vErrResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xe2\b\n" +
	"\rSampleService\x123\n" +
	"\x05Hello\x12\r.sample.Empty\x1a\x19.sample.HelloResponseBody\"\x00\x12S\n" +
	"\fHelloAddText\x12\x1f.sample.HelloAddTextRequestBody\x1a .sample.HelloAddTextResponseBody\"\x00\x12d\n" +
	"\x11HelloServerStream\x12$.sample.HelloServerStreamRequestBody\x1a%.sample.HelloServerStreamResponseBody\"\x000\x01\x12d\n" +
	"\x11HelloClientStream\x12$.sample.HelloClientStreamRequestBody\x1a%.sample.HelloClientStreamResponseBody\"\x00(\x01\x12{\n" +
	"\x18HelloBidirectionalStream\x12+.sample.HelloBidirectionalStreamRequestBody\x1a,.sample.HelloBidirectionalStreamResponseBody\"\x00(\x010\x01\x12\xc2\x01\n" +
	"\bHelloApi\x12\r.sample.Empty\x1a\x19.sample.HelloResponseBody\"\x8b\x01\x92AsJq\n" +
	"\x03500\x12j\n" +
	"\x15Internal Server Error\x12\x17\n" +
	"\x15\x1a\x13.sample.ErrResponse\"8\n" +
	"\x10application/json\x12${\"message\": \"Internal Server Error\"}\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/hello\x12\xb8\x03\n" +
	"\x0fHelloAddTextApi\x12\x1f.sample.HelloAddTextRequestBody\x1a .sample.HelloAddTextResponseBody\"\xe1\x02\x92A\xc5\x02J]\n" +
	"\x03400\x12V\n" +
	"\vBad Request\x12\x17\n" +
	"\x15\x1a\x13.sample.ErrResponse\".\n" +
	"\x10application/json\x12\x1a{\"message\": \"Bad Request\"}J_\n" +
	"\x03401\x12X\n" +
	"\fUnauthorized\x12\x17\n" +
	"\x15\x1a\x13.sample.ErrResponse\"/\n" +
	"\x10application/json\x12\x1b{\"message\": \"Unauthorized\"}Jq\n" +
	"\x03500\x12j\n" +
	"\x15Internal Server Error\x12\x17\n" +
	"\x15\x1a\x13.sample.ErrResponse\"8\n" +
	"\x10application/json\x12${\"message\": \"Internal Server Error\"}b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/helloB\xc8\x01\x92A\xb9\x01\n" +
	"\x032.0\x124\n" +
	"\fgRPC-Gateway\x12\x1fgRPC-GatewayのOpenAPI仕様書2\x031.0\x1a\x0elocalhost:8080*\x01\x01Zi\n" +
	"g\n" +
	"\n" +
	"BearerAuth\x12Y\b\x02\x12DEnter the token with the `Bearer ` prefix, e.g., `Bearer abcde12345`\x1a\rAuthorization \x02Z\tpb/sampleb\x06proto3"

var (
	file_proto_sample_sample_proto_rawDescOnce sync.Once
	file_proto_sample_sample_proto_rawDescData []byte
)

func file_proto_sample_sample_proto_rawDescGZIP() []byte {
	file_proto_sample_sample_proto_rawDescOnce.Do(func() {
		file_proto_sample_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sample_sample_proto_rawDesc), len(file_proto_sample_sample_proto_rawDesc)))
	})
	return file_proto_sample_sample_proto_rawDescData
}

var file_proto_sample_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_sample_sample_proto_goTypes = []any{
	(*Empty)(nil),                                // 0: sample.Empty
	(*HelloResponseBody)(nil),                    // 1: sample.HelloResponseBody
	(*HelloAddTextRequestBody)(nil),              // 2: sample.HelloAddTextRequestBody
	(*HelloAddTextResponseBody)(nil),             // 3: sample.HelloAddTextResponseBody
	(*HelloServerStreamRequestBody)(nil),         // 4: sample.HelloServerStreamRequestBody
	(*HelloServerStreamResponseBody)(nil),        // 5: sample.HelloServerStreamResponseBody
	(*HelloClientStreamRequestBody)(nil),         // 6: sample.HelloClientStreamRequestBody
	(*HelloClientStreamResponseBody)(nil),        // 7: sample.HelloClientStreamResponseBody
	(*HelloBidirectionalStreamRequestBody)(nil),  // 8: sample.HelloBidirectionalStreamRequestBody
	(*HelloBidirectionalStreamResponseBody)(nil), // 9: sample.HelloBidirectionalStreamResponseBody
	(*ErrResponse)(nil),                          // 10: sample.ErrResponse
}
var file_proto_sample_sample_proto_depIdxs = []int32{
	0, // 0: sample.SampleService.Hello:input_type -> sample.Empty
	2, // 1: sample.SampleService.HelloAddText:input_type -> sample.HelloAddTextRequestBody
	4, // 2: sample.SampleService.HelloServerStream:input_type -> sample.HelloServerStreamRequestBody
	6, // 3: sample.SampleService.HelloClientStream:input_type -> sample.HelloClientStreamRequestBody
	8, // 4: sample.SampleService.HelloBidirectionalStream:input_type -> sample.HelloBidirectionalStreamRequestBody
	0, // 5: sample.SampleService.HelloApi:input_type -> sample.Empty
	2, // 6: sample.SampleService.HelloAddTextApi:input_type -> sample.HelloAddTextRequestBody
	1, // 7: sample.SampleService.Hello:output_type -> sample.HelloResponseBody
	3, // 8: sample.SampleService.HelloAddText:output_type -> sample.HelloAddTextResponseBody
	5, // 9: sample.SampleService.HelloServerStream:output_type -> sample.HelloServerStreamResponseBody
	7, // 10: sample.SampleService.HelloClientStream:output_type -> sample.HelloClientStreamResponseBody
	9, // 11: sample.SampleService.HelloBidirectionalStream:output_type -> sample.HelloBidirectionalStreamResponseBody
	1, // 12: sample.SampleService.HelloApi:output_type -> sample.HelloResponseBody
	3, // 13: sample.SampleService.HelloAddTextApi:output_type -> sample.HelloAddTextResponseBody
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sample_sample_proto_init() }
func file_proto_sample_sample_proto_init() {
	if File_proto_sample_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sample_sample_proto_rawDesc), len(file_proto_sample_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sample_sample_proto_goTypes,
		DependencyIndexes: file_proto_sample_sample_proto_depIdxs,
		MessageInfos:      file_proto_sample_sample_proto_msgTypes,
	}.Build()
	File_proto_sample_sample_proto = out.File
	file_proto_sample_sample_proto_goTypes = nil
	file_proto_sample_sample_proto_depIdxs = nil
}
